version: '3.8'

services:
  nginx:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.nginx
    image: nginx:alpine
    working_dir: ${DOCKER_APP_BASE_PATH}
    volumes:
      - .:${DOCKER_APP_BASE_PATH}
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${DOCKER_EXPOSE_PORT_NGINX}:80

  php-fpm:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.php-fpm
    build: .docker/php-fpm
    working_dir: ${DOCKER_APP_BASE_PATH}
    volumes:
      - ./:${DOCKER_APP_BASE_PATH}

  mysql:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_EXPOSE_PORT_DB}:3306

  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
