version: '3.8'

services:
  nginx:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.nginx
    image: nginx:alpine
    working_dir: ${DOCKER_APP_BASE_PATH}
    volumes:
      - .:${DOCKER_APP_BASE_PATH}
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"

  php-fpm:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.php-fpm
    build: .docker/php-fpm
    working_dir: ${DOCKER_APP_BASE_PATH}
    volumes:
      - ./:${DOCKER_APP_BASE_PATH}

  mysql:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${DOCKER_EXPOSE_PORT_MYSQL}:3306

  redis:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.redis
    image: redis:alpine
    ports:
      - ${DOCKER_EXPOSE_PORT_REDIS}:6379

  rabbitmq:
    container_name: ${APP_ENV}.${DOCKER_APP_NAME}.rabbitmq
    image: rabbitmq:management
    ports:
      - ${DOCKER_EXPOSE_PORT_RABBITMQ}:5672
      - ${DOCKER_EXPOSE_PORT_RABBITMQ_ADMIN}:15672
